# -Dspring.profiles.active=dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:C:/Users/Public/db/test.db

server:
  port: 8081

walter:
  dist: C:/Users/walter/Downloads/mybatis_code_gen_dist

#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://127.0.0.1:3306/user_info?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&useSSL=false&characterEncoding=utf8
#    username: root
#    password: 123456
#

---

# -Dspring.profiles.active=test
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.sqlite.JDBC
    url: jdbc:sqlite:/projects/db/test.db

server:
  port: 8081

walter:
  dist: /projects/mybatis_code_gen_dist
